# Generated by Django 5.0 on 2023-12-27 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipes_name', models.CharField(max_length=100)),
                ('recipes_description', models.TextField()),
                ('recipes_image', models.ImageField(upload_to='recipes')),
            ],
        ),
    ]
