# Generated by Django 5.0 on 2023-12-27 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipes',
        ),
    ]
